version: '3.8'
services:
  wordpress:
    image: wordpress:latest
    ports:
      - "80"
    volumes:
      - wordpress-files:/var/www/html
      - yato-theme-data:/var/www/html/wp-content/themes/yato-theme
      - yato-plugin-data:/var/www/html/wp-content/plugins/yato_postypes
    environment:
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DB_NAME: wordpress
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:11
    volumes:
      - mariadb-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: password

volumes:
  wordpress-files:
  mariadb-data:
  yato-theme-data: 
  yato-plugin-data: