version: '3.8'
services:
  wordpress:
    build: .
    ports:
      - "80"
    volumes:
      - wordpress-data-v2:/var/www/html
      - ./themes/yato-theme:/var/www/html/wp-content/themes/yato-theme
      - ./plugins/yato_postypes:/var/www/html/wp-content/plugins/yato_postypes
    environment:
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DB_NAME: wordpress
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:11
    volumes:
      - mariadb-data-v2:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: password

volumes:
  wordpress-data-v2:
  mariadb-data-v2: